name: OV Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'LICENCE'
      - 'CONTRIBUTION.md'
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'LICENCE'
      - 'CONTRIBUTION.md'
      - 'README.md'
  schedule:
    - cron: '45 20 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    timeout-minutes: 100
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [windows]
        config: [release]
        compiler: [cl]
        platform: [x86_64]
        include:
          # Self-hosted OV tests
          - warnings-as-errors: false
            runs-on: [Windows, self-hosted, kaizhang-local]
    runs-on: ${{ matrix.runs-on }}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: '0'
    - name: Setup
      uses: ./.github/actions/common-setup
      with:
        os: ${{matrix.os}}
        compiler: ${{matrix.compiler}}
        platform: ${{matrix.platform}}
        config: ${{matrix.config}}
        build-llvm: false
    - name: Build Slang
      run: |
        cmake --preset default --fresh \
          -DSLANG_SLANG_LLVM_FLAVOR=DISABLE \
          -DCMAKE_COMPILE_WARNING_AS_ERROR=${{matrix.warnings-as-errors}} \
          -DSLANG_ENABLE_CUDA=0 \
          -DSLANG_ENABLE_EXAMPLES=0 \
          -DSLANG_ENABLE_GFX=0 \
          -DSLANG_ENABLE_TESTS=0
        cmake --workflow --preset "${{matrix.config}}"
    - name: setup-OV
      shell: powershell
      run: |
        Copy-Item -Path 'C:\ov-kit-package' -Destination '.\' -Recurse
    - name: Copy Slang to OV
      shell: powershell
      run: |
        Copy-Item -Path 'build\Release\bin\slang.dll' -Destination '.\ov-kit-package\_build\windows-x86_64\release\plugins\gpu.foundation\'
        Copy-Item -Path 'build\Release\bin\slang-glslang.dll' -Destination '.\ov-kit-package\_build\windows-x86_64\release\plugins\gpu.foundation\'
    - name: OV Test Per Commit
      if: github.event_name != 'schedule'
      shell: powershell
      run: |
        # cd .\ov-kit-package\
        # .\_build\windows-x86_64\release\test.unit.exe -tc="*rtxStartup-default*" -r=junit --junit-output=./junit.xml
    - name: OV Test Nightly
      if: github.event_name == 'schedule'
      shell: powershell
      run: |
        cd .\ov-kit-package\
        .\_build\windows-x86_64\release\test.unit.exe -tc="*rtxStartup-mdlAsLibrary-obfuscated*" -r=junit --junit-output=./junit.xml
    - name: Publish Test Results
      uses: mikepenz/action-junit-report@v4
      if: always()
      with:
        report_paths: |
          .\ov-kit-package\*.xml
