on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: centos7-gcc9 Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: '0'

      # build the binary in docker image
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: slangdeveloper/centos7-gcc9:cmake
            options: -v ${{ github.workspace }}:/home/app -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
            run: |
              source /opt/rh/devtoolset-9/enable
              cd /home/app
              git config --global --add safe.directory /home/app
              /cmake-3.30.0-linux-x86_64/bin/cmake --preset default
              /cmake-3.30.0-linux-x86_64/bin/cmake --build --preset release

      - name: CreatePackages
        id: build
        run: |
            echo "creating binary archieves..."
            export SLANG_OS_NAME=linux
            export SLANG_ARCH_NAME=`uname -p`
            export TAG_NAME=`git describe --tags`
            export SLANG_TAG=${TAG_NAME#v}
            echo "tag:$TAG_NAME"
            echo "slang-tag:$SLANG_TAG"
            export SLANG_BINARY_ARCHIVE=slang-${SLANG_TAG}-${SLANG_OS_NAME}-${SLANG_ARCH_NAME}-glibc-2.17.zip
            export SLANG_BINARY_ARCHIVE_TAR=slang-${SLANG_TAG}-${SLANG_OS_NAME}-${SLANG_ARCH_NAME}-glibc-2.17.tar.gz
            echo "creating zip"
            zip -r ${SLANG_BINARY_ARCHIVE} build/Release/bin/slangc build/Release/bin/slangd build/Release/lib/libslang.so build/Release/lib/libslang-glslang.so build/Release/lib/libgfx.so docs/*.md README.md LICENSE slang.h slang-com-helper.h slang-com-ptr.h slang-tag-version.h slang-gfx.h prelude/*.h
            echo "creating tar"
            tar -czf ${SLANG_BINARY_ARCHIVE_TAR} build/Release/bin/slangc build/Release/bin/slangd build/Release/lib/libslang.so build/Release/lib/libslang-glslang.so build/Release/lib/libgfx.so docs/*.md README.md LICENSE slang.h slang-com-helper.h slang-com-ptr.h slang-tag-version.h slang-gfx.h prelude/*.h
            echo "SLANG_BINARY_ARCHIVE=${SLANG_BINARY_ARCHIVE}" >> $GITHUB_OUTPUT
            echo "SLANG_BINARY_ARCHIVE_TAR=${SLANG_BINARY_ARCHIVE_TAR}" >> $GITHUB_OUTPUT
      - name: UploadBinary
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.build.outputs.SLANG_BINARY_ARCHIVE }}
            ${{ steps.build.outputs.SLANG_BINARY_ARCHIVE_TAR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
